### ISSUE TITLE
Classes\Mails folder

### ISSUE THREAD

**Issue by mjauvin** [skydiver/wn-forms-plugin#13]
the "Mails" folder under "classes" needs to be lowercase, otherwise the classes are not found when calling App::makeWidth().

**Comment by mjauvin** [comment]
Actually a duplicate of #9 
Not sure why it was closed since the problem has NOT been resolved.

**Comment by NecroMan** [comment]
The problem is still here. I spent almost an hour trying to figure out why it doesn't work on the production server...
