### ISSUE TITLE
Send email notification error : "Class Martin\Forms\Classes\Mails\Notification does not exist" 

### ISSUE THREAD

**Issue by willouch** [skydiver/wn-forms-plugin#7]
"Class Martin\Forms\Classes\Mails\Notification does not exist" on line 63 of /vendor/winter/storm/src/Foundation/Maker.php

**Comment by willouch** [comment]
Resolved by rename classes directories Mails and FilePond in lowecase

**Comment by damsfx** [comment]
Got the same issue with WinterCMS 1.1.7

**Comment by willouch** [comment]
avec 1.1.8 same issue !
Pour info j'ai résolu le souci en renommant les dossiers Mails et FilePond en minuscule soit "mails/" et "filepond/"
Resolved by rename classes directories Mails and FilePond in lowecase
Pull request = https://github.com/skydiver/wn-forms-plugin/pull/8
